name: Task
description: Create a task.
title: "[Task]: "
labels: ["task"]
type: "task"
body:
  - type: textarea
    id: desc-task
    attributes:
      label: Expectations
      description: What do you expect for the final result?
    validations:
      required: true

  - type: textarea
    id: todo-task
    attributes:
      label: Todo
      description: A checklist of things to do
      value: |
        - [ ] Item 1
        - [ ] Item 2
        - [ ] Item 3
        - [ ] Item 4
    validations:
      required: true